set -e;
mkdir -p classes;
clojure -M:test-runner-cognitect;
npm i;
shadow-cljs compile ci;
npx karma start --single-run;
clojure -e "(compile 'tech.thomas-sojka.shopping-cards.main)";
npm run css;
shadow-cljs compile app;
clojure -M:uberdeps;
# scp target/shopping-cards.jar pi@ubi-hub:/home/pi;
# ssh pi@ubi-hub sudo systemctl restart shoppinglist.service;
