set -e;
mkdir -p classes;
clojure -M:test-runner-cognitect;
npm i;
shadow-cljs compile ci;
npx karma start --single-run;
clojure -e "(compile 'tech.thomas-sojka.shopping-cards.system)";
shadow-cljs -Afe release app;
clojure -M:uberdeps --aliases release;
scp target/shopping-cards.jar pi@ubi-hub:/home/pi;
ssh pi@ubi-hub sudo systemctl restart shoppinglist.service;
