name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.0-beta1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: npm install
      run: npm install
    - name: Build Tests
      run: npx shadow-cljs compile ci
    - name: Run Tests
      run: npx karma start --single-run;
