name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.3
      with:
        cli: 1.11.1
        bb: 1.3.188
        clj-kondo: 2023.10.20
    - name: Run clj-kondo
      run: clj-kondo --lint src
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.3.0
    - name: npm install
      run: npm install
    - name: Run FE Tests
      run: bb test:fe
