name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.7
      with:
        cli: 1.10.1.693
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2022.01.15'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: npm install
      run: npm install
    - name: Build Tests
      run: npx shadow-cljs compile ci
    - name: Run FE Tests
      run: npx karma start --single-run;
